version: "3.7"

services:
  base:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/app
    user: node
    working_dir: /app
    environment:
      ENVIRONMENT: test
      ANVIL_MNEMONIC: test test test test test test test test test test test junk
      ANVIL_HOST: anvil
      ANVIL_PORT: 8545
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    
  test-runner:
    extends:
      service: base
    depends_on:
      - anvil
      - db
      - localstack
    command: "npm run test"

  anvil:
    image: ghcr.io/foundry-rs/foundry
    entrypoint: anvil
    command:
      [
        "--chain-id", "100",
        "--balance", "1000000",
        "--host", "0.0.0.0",
      ]
  
  db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
